# SPDX-License-Identifier: MIT
"""Reviewed manifests for projects proposed in issue #13."""

from __future__ import annotations

from .core import (
    IntegrationMode,
    ManifestPlugin,
    OptimizationDescriptor,
    OptimizationKind,
    OptimizationMaturity,
    OptimizationRegistry,
)


BUILTIN_DESCRIPTORS = (
    OptimizationDescriptor(
        id="lmcache",
        name="LMCache",
        source_url="https://github.com/LMCache/LMCache",
        kind=OptimizationKind.CACHE_STORAGE,
        maturity=OptimizationMaturity.EXPERIMENTAL,
        integration_mode=IntegrationMode.EXTERNAL_SERVICE,
        license="Apache-2.0",
        summary="Reusable, tiered KV-cache storage for vLLM serving workloads.",
        supported_engines=("vllm",),
        supported_compute=("cuda", "rocm"),
        supported_os=("linux",),
        supported_kv_formats=("fp16", "bf16", "fp8"),
        required_modules=("lmcache",),
        required_executables=("lmcache",),
        limitations=(
            "Custom Multi-TurboQuant cache layouts are not claimed compatible without a dedicated SERDE.",
            "Benefits depend on reusable prefixes or cache sharing; one-shot prompts can regress.",
        ),
    ),
    OptimizationDescriptor(
        id="maru",
        name="Maru",
        source_url="https://github.com/xcena-dev/maru",
        kind=OptimizationKind.CACHE_STORAGE,
        maturity=OptimizationMaturity.EXPERIMENTAL,
        integration_mode=IntegrationMode.EXTERNAL_SERVICE,
        license="Apache-2.0",
        summary="LMCache storage backed by CXL shared memory.",
        supported_engines=("vllm",),
        supported_compute=("cuda",),
        supported_os=("linux",),
        supported_kv_formats=("fp16", "bf16", "fp8"),
        required_modules=("maru_lmcache",),
        required_executables=("maru-server",),
        required_capabilities=("cxl_devdax",),
        requires=("lmcache",),
        min_python=(3, 12),
        limitations=("Requires CXL memory exposed through /dev/dax devices.",),
    ),
    OptimizationDescriptor(
        id="minference",
        name="MInference",
        source_url="https://github.com/microsoft/MInference",
        kind=OptimizationKind.PREFILL,
        maturity=OptimizationMaturity.EXPERIMENTAL,
        integration_mode=IntegrationMode.OPTIONAL_PYTHON,
        license="MIT",
        summary="Sparse long-context prefill kernels for selected model patterns.",
        supported_engines=("vllm",),
        supported_compute=("cuda",),
        supported_os=("linux",),
        supported_kv_formats=("fp16", "bf16", "fp8"),
        required_modules=("minference",),
        conflicts=("speculative_prefill",),
        limitations=(
            "Uses runtime-specific patches and model-specific sparse-attention patterns.",
            "Must be qualified against the exact vLLM, Torch, Triton, and model versions.",
        ),
    ),
    OptimizationDescriptor(
        id="sageattention",
        name="SageAttention",
        source_url="https://github.com/thu-ml/SageAttention",
        kind=OptimizationKind.ATTENTION_BACKEND,
        maturity=OptimizationMaturity.EXPERIMENTAL,
        integration_mode=IntegrationMode.OPTIONAL_PYTHON,
        license="Apache-2.0",
        summary="Quantized CUDA attention kernels for compatible PyTorch models.",
        supported_engines=("python",),
        supported_compute=("cuda",),
        supported_os=("linux",),
        supported_kv_formats=("fp16", "bf16"),
        required_modules=("sageattention",),
        conflicts=("flashattention",),
        limitations=(
            "No maintained llama.cpp or vLLM connector is provided upstream.",
            "Global scaled_dot_product_attention replacement is not compatible with every model.",
        ),
    ),
    OptimizationDescriptor(
        id="flashattention",
        name="FlashAttention 2",
        source_url="https://github.com/Dao-AILab/flash-attention",
        kind=OptimizationKind.ATTENTION_BACKEND,
        maturity=OptimizationMaturity.EXPERIMENTAL,
        integration_mode=IntegrationMode.OPTIONAL_PYTHON,
        license="BSD-3-Clause",
        summary="Exact fused CUDA attention kernels for compatible PyTorch runtimes.",
        supported_engines=("python", "fastdms"),
        supported_compute=("cuda",),
        supported_os=("linux",),
        supported_kv_formats=("fp16", "bf16"),
        required_modules=("flash_attn",),
        conflicts=("sageattention",),
        limitations=(
            "PyTorch, CUDA toolkit, GPU architecture, and wheel ABI must be compatible.",
            "Installation may compile native CUDA extensions when no compatible wheel exists.",
        ),
    ),
    OptimizationDescriptor(
        id="speculative_prefill",
        name="Speculative Prefill",
        source_url="https://github.com/Jingyu6/speculative_prefill",
        kind=OptimizationKind.PREFILL,
        maturity=OptimizationMaturity.EXPERIMENTAL,
        integration_mode=IntegrationMode.OPTIONAL_PYTHON,
        license="MIT",
        summary="Draft-model token selection intended to reduce long-prompt TTFT.",
        supported_engines=("vllm",),
        supported_compute=("cuda",),
        supported_os=("linux",),
        supported_kv_formats=("fp16", "bf16", "fp8"),
        required_modules=("speculative_prefill",),
        conflicts=("minference",),
        limitations=(
            "Upstream is a monkeypatch pinned to vLLM 0.6.3.post1 and disables chunked prefill.",
            "Requires a compatible draft model and workload-specific quality evaluation.",
        ),
    ),
    OptimizationDescriptor(
        id="fastdms",
        name="FastDMS",
        source_url="https://github.com/shisa-ai/FastDMS",
        kind=OptimizationKind.TOKEN_POLICY,
        maturity=OptimizationMaturity.EXPERIMENTAL,
        integration_mode=IntegrationMode.EXTERNAL_SERVICE,
        license="MIT",
        summary="Standalone compact-DMS engine for DMS-trained checkpoints.",
        supported_engines=("fastdms",),
        supported_compute=("cuda",),
        supported_os=("linux",),
        required_modules=("fastdms", "flash_attn"),
        requires=("flashattention",),
        conflicts=("triattention", "rocketkv"),
        limitations=(
            "Upstream documents that a real vLLM port requires scheduler and cache-manager surgery.",
            "Only DMS-trained checkpoints are supported.",
        ),
    ),
    OptimizationDescriptor(
        id="rocketkv",
        name="RocketKV",
        source_url="https://github.com/NVlabs/RocketKV",
        kind=OptimizationKind.TOKEN_POLICY,
        maturity=OptimizationMaturity.RESEARCH,
        integration_mode=IntegrationMode.RESEARCH_ONLY,
        license="NVIDIA non-commercial research license",
        summary="Two-stage KV token eviction research implementation based on gpt-fast.",
        supported_engines=("gpt-fast",),
        supported_compute=("cuda",),
        supported_os=("linux",),
        conflicts=("triattention", "fastdms"),
        limitations=(
            "The source license limits derivative use to non-commercial research or evaluation.",
            "The repository is a research snapshot with no release or maintained serving connector.",
        ),
    ),
    OptimizationDescriptor(
        id="lexico",
        name="Lexico",
        source_url="https://github.com/krafton-ai/lexico",
        kind=OptimizationKind.CACHE_REPRESENTATION,
        maturity=OptimizationMaturity.RESEARCH,
        integration_mode=IntegrationMode.RESEARCH_ONLY,
        license="Apache-2.0",
        summary="Sparse-coded KV representation using model-specific dictionaries.",
        supported_engines=("transformers",),
        supported_compute=("cuda",),
        supported_os=("linux",),
        conflicts=("kvarn", "turboquant", "isoquant", "planarquant"),
        limitations=("Upstream marks the implementation WIP and requires dictionary training per model.",),
    ),
    OptimizationDescriptor(
        id="adadecode",
        name="AdaDecode",
        source_url="https://github.com/weizhepei/AdaDecode",
        kind=OptimizationKind.DECODE,
        maturity=OptimizationMaturity.BLOCKED,
        integration_mode=IntegrationMode.RESEARCH_ONLY,
        license="No repository license",
        summary="Adaptive layer-parallel decoding with trained intermediate prediction heads.",
        supported_engines=("transformers",),
        supported_compute=("cuda",),
        supported_os=("linux",),
        limitations=(
            "No source-code license is present, so code cannot be incorporated.",
            "Requires task/model-specific trained prediction heads and execution-graph changes.",
        ),
    ),
    OptimizationDescriptor(
        id="resonance_yarn",
        name="Resonance YaRN",
        source_url="https://github.com/sheryc/resonance_rope",
        kind=OptimizationKind.POSITION_ENCODING,
        maturity=OptimizationMaturity.RESEARCH,
        integration_mode=IntegrationMode.NATIVE_BACKEND_REQUIRED,
        license="Apache-2.0",
        summary="Resonance wavelength rounding applied to YaRN positional embeddings.",
        supported_engines=("transformers",),
        supported_compute=("cuda",),
        supported_os=("linux",),
        limitations=(
            "The provided llama_finetuning code is a Hugging Face training fork, not a llama.cpp plugin.",
            "llama.cpp or Godzilla requires a native RoPE implementation and model-level validation.",
        ),
    ),
)


def create_builtin_registry() -> OptimizationRegistry:
    registry = OptimizationRegistry()
    for descriptor in BUILTIN_DESCRIPTORS:
        registry.register(ManifestPlugin(descriptor))
    return registry
