# SPDX-License-Identifier: MIT
"""Reviewed manifests for projects proposed in issue #13."""

from __future__ import annotations

from .core import (
    IntegrationMode,
    ManifestPlugin,
    OptimizationDescriptor,
    OptimizationKind,
    OptimizationMaturity,
    OptimizationRegistry,
    QualityRisk,
)


BUILTIN_DESCRIPTORS = (
    OptimizationDescriptor(
        id="lmcache",
        name="LMCache",
        source_url="https://github.com/LMCache/LMCache",
        kind=OptimizationKind.CACHE_STORAGE,
        maturity=OptimizationMaturity.EXPERIMENTAL,
        integration_mode=IntegrationMode.EXTERNAL_SERVICE,
        license="Apache-2.0",
        summary="Reusable, tiered KV-cache storage for vLLM serving workloads.",
        supported_engines=("vllm",),
        supported_compute=("cuda", "rocm"),
        supported_os=("linux",),
        supported_kv_formats=("fp16", "bf16", "fp8"),
        required_modules=("lmcache",),
        required_executables=("lmcache",),
        limitations=(
            "Custom Multi-TurboQuant cache layouts are not claimed compatible without a dedicated SERDE.",
            "Benefits depend on reusable prefixes or cache sharing; one-shot prompts can regress.",
        ),
        composition_domains=("cache_storage",),
    ),
    OptimizationDescriptor(
        id="maru",
        name="Maru",
        source_url="https://github.com/xcena-dev/maru",
        kind=OptimizationKind.CACHE_STORAGE,
        maturity=OptimizationMaturity.EXPERIMENTAL,
        integration_mode=IntegrationMode.EXTERNAL_SERVICE,
        license="Apache-2.0",
        summary="LMCache storage backed by CXL shared memory.",
        supported_engines=("vllm",),
        supported_compute=("cuda",),
        supported_os=("linux",),
        supported_kv_formats=("fp16", "bf16", "fp8"),
        required_modules=("maru_lmcache",),
        required_executables=("maru-server",),
        required_capabilities=("cxl_devdax",),
        requires=("lmcache",),
        min_python=(3, 12),
        limitations=("Requires CXL memory exposed through /dev/dax devices.",),
        composition_domains=("cache_storage_backend",),
    ),
    OptimizationDescriptor(
        id="minference",
        name="MInference",
        source_url="https://github.com/microsoft/MInference",
        kind=OptimizationKind.PREFILL,
        maturity=OptimizationMaturity.EXPERIMENTAL,
        integration_mode=IntegrationMode.OPTIONAL_PYTHON,
        license="MIT",
        summary="Sparse long-context prefill kernels for selected model patterns.",
        supported_engines=("vllm",),
        supported_compute=("cuda",),
        supported_os=("linux",),
        supported_kv_formats=("fp16", "bf16", "fp8"),
        required_modules=("minference",),
        conflicts=("speculative_prefill",),
        limitations=(
            "Uses runtime-specific patches and model-specific sparse-attention patterns.",
            "Must be qualified against the exact vLLM, Torch, Triton, and model versions.",
        ),
        composition_domains=("prefill_attention",),
    ),
    OptimizationDescriptor(
        id="sageattention",
        name="SageAttention",
        source_url="https://github.com/thu-ml/SageAttention",
        kind=OptimizationKind.ATTENTION_BACKEND,
        maturity=OptimizationMaturity.EXPERIMENTAL,
        integration_mode=IntegrationMode.OPTIONAL_PYTHON,
        license="Apache-2.0",
        summary="Quantized CUDA attention kernels for compatible PyTorch models.",
        supported_engines=("python",),
        supported_compute=("cuda",),
        supported_os=("linux",),
        supported_kv_formats=("fp16", "bf16"),
        required_modules=("sageattention",),
        conflicts=("flashattention",),
        limitations=(
            "No maintained llama.cpp or vLLM connector is provided upstream.",
            "Global scaled_dot_product_attention replacement is not compatible with every model.",
        ),
        composition_domains=("attention_kernel",),
    ),
    OptimizationDescriptor(
        id="flashattention",
        name="FlashAttention 2",
        source_url="https://github.com/Dao-AILab/flash-attention",
        kind=OptimizationKind.ATTENTION_BACKEND,
        maturity=OptimizationMaturity.EXPERIMENTAL,
        integration_mode=IntegrationMode.OPTIONAL_PYTHON,
        license="BSD-3-Clause",
        summary="Exact fused CUDA attention kernels for compatible PyTorch runtimes.",
        supported_engines=("python", "fastdms"),
        supported_compute=("cuda",),
        supported_os=("linux",),
        supported_kv_formats=("fp16", "bf16"),
        required_modules=("flash_attn",),
        conflicts=("sageattention",),
        limitations=(
            "PyTorch, CUDA toolkit, GPU architecture, and wheel ABI must be compatible.",
            "Installation may compile native CUDA extensions when no compatible wheel exists.",
        ),
        composition_domains=("attention_kernel",),
    ),
    OptimizationDescriptor(
        id="speculative_prefill",
        name="Speculative Prefill",
        source_url="https://github.com/Jingyu6/speculative_prefill",
        kind=OptimizationKind.PREFILL,
        maturity=OptimizationMaturity.EXPERIMENTAL,
        integration_mode=IntegrationMode.OPTIONAL_PYTHON,
        license="MIT",
        summary="Draft-model token selection intended to reduce long-prompt TTFT.",
        supported_engines=("vllm",),
        supported_compute=("cuda",),
        supported_os=("linux",),
        supported_kv_formats=("fp16", "bf16", "fp8"),
        required_modules=("speculative_prefill",),
        conflicts=("minference",),
        limitations=(
            "Upstream is a monkeypatch pinned to vLLM 0.6.3.post1 and disables chunked prefill.",
            "Requires a compatible draft model and workload-specific quality evaluation.",
        ),
        composition_domains=("prefill_policy",),
    ),
    OptimizationDescriptor(
        id="fastdms",
        name="FastDMS",
        source_url="https://github.com/shisa-ai/FastDMS",
        kind=OptimizationKind.TOKEN_POLICY,
        maturity=OptimizationMaturity.EXPERIMENTAL,
        integration_mode=IntegrationMode.EXTERNAL_SERVICE,
        license="MIT",
        summary="Standalone compact-DMS engine for DMS-trained checkpoints.",
        supported_engines=("fastdms",),
        supported_compute=("cuda",),
        supported_os=("linux",),
        required_modules=("fastdms", "flash_attn"),
        requires=("flashattention",),
        conflicts=("triattention", "rocketkv"),
        limitations=(
            "Upstream documents that a real vLLM port requires scheduler and cache-manager surgery.",
            "Only DMS-trained checkpoints are supported.",
        ),
        composition_domains=("runtime_engine",),
    ),
    OptimizationDescriptor(
        id="rocketkv",
        name="RocketKV",
        source_url="https://github.com/NVlabs/RocketKV",
        kind=OptimizationKind.TOKEN_POLICY,
        maturity=OptimizationMaturity.RESEARCH,
        integration_mode=IntegrationMode.RESEARCH_ONLY,
        license="NVIDIA non-commercial research license",
        summary="Two-stage KV token eviction research implementation based on gpt-fast.",
        supported_engines=("gpt-fast",),
        supported_compute=("cuda",),
        supported_os=("linux",),
        conflicts=("triattention", "fastdms"),
        limitations=(
            "The source license limits derivative use to non-commercial research or evaluation.",
            "The repository is a research snapshot with no release or maintained serving connector.",
        ),
        composition_domains=("kv_selection",),
    ),
    OptimizationDescriptor(
        id="triattention",
        name="TriAttention",
        source_url="https://github.com/WeianMao/triattention",
        kind=OptimizationKind.TOKEN_POLICY,
        maturity=OptimizationMaturity.EXPERIMENTAL,
        integration_mode=IntegrationMode.OPTIONAL_PYTHON,
        license="Apache-2.0",
        summary="Model-specific KV selection for vLLM, SGLang, and patched Godzilla runtimes.",
        supported_engines=("godzilla", "vllm", "sglang"),
        supported_compute=("cuda",),
        supported_os=("linux",),
        supported_kv_formats=("fp16", "bf16"),
        required_modules=("triattention",),
        conflicts=("kvarn", "fastdms", "rocketkv", "lmcache"),
        limitations=(
            "Calibration requires the matching Hugging Face checkpoint and a non-empty text corpus.",
            "Official vLLM and SGLang runtime paths require prefix/radix caching to be disabled.",
            "Speculative decoding is not a reviewed composition with TriAttention cache compaction.",
            "Godzilla rejects KVarN plus TriAttention until KVarN-aware pruning is implemented.",
            "domvox TRIA v2 conversion is lossy and requires explicit acknowledgement.",
        ),
        composition_domains=("kv_selection",),
        reviewed_source_commit="a4bc3c8f709db60f016ef42c3feb290fd0c00c1b",
    ),
    OptimizationDescriptor(
        id="gigatoken",
        name="Gigatoken calibration tokenizer",
        source_url="https://github.com/marcelroed/gigatoken",
        kind=OptimizationKind.TOKENIZER,
        maturity=OptimizationMaturity.EXPERIMENTAL,
        integration_mode=IntegrationMode.OPTIONAL_PYTHON,
        license="MIT",
        summary="Opt-in tokenizer acceleration for reviewed TriAttention calibration paths.",
        supported_engines=("godzilla",),
        supported_compute=("cuda",),
        supported_os=("linux",),
        required_modules=("gigatoken",),
        requires=("triattention",),
        limitations=(
            "Every token ID must match Hugging Face for the complete selected calibration text.",
            "The Python backend does not enable Gigatoken in the inference runtime.",
        ),
        composition_domains=("calibration_tokenizer",),
    ),
    OptimizationDescriptor(
        id="cuda_weight_share",
        name="CUDA LLM Weight Share",
        source_url="https://github.com/pontostroy/cuda-llm-weight-share",
        kind=OptimizationKind.RESOURCE_SHARING,
        maturity=OptimizationMaturity.EXPERIMENTAL,
        integration_mode=IntegrationMode.PRELOAD_LIBRARY,
        license="MIT",
        summary="Linux LD_PRELOAD helper that shares one model-weight CUDA allocation.",
        supported_engines=("llamacpp", "godzilla"),
        supported_compute=("cuda",),
        supported_os=("linux",),
        supported_architectures=("x86_64", "amd64"),
        required_executables=("gcc",),
        limitations=(
            "MODEL_SIZE=0 reconnaissance must identify the exact allocation before production use.",
            "It shares one model-weight allocation, not KV cache, and requires a unique IPC name.",
            "All participating processes must use the same compatible model and CUDA environment.",
        ),
        composition_domains=("weight_allocation",),
    ),
    OptimizationDescriptor(
        id="lexico",
        name="Lexico",
        source_url="https://github.com/krafton-ai/lexico",
        kind=OptimizationKind.CACHE_REPRESENTATION,
        maturity=OptimizationMaturity.RESEARCH,
        integration_mode=IntegrationMode.RESEARCH_ONLY,
        license="Apache-2.0",
        summary="Sparse-coded KV representation using model-specific dictionaries.",
        supported_engines=("transformers",),
        supported_compute=("cuda",),
        supported_os=("linux",),
        conflicts=("kvarn", "turboquant", "isoquant", "planarquant"),
        limitations=("Upstream marks the implementation WIP and requires dictionary training per model.",),
        composition_domains=("kv_representation",),
    ),
    OptimizationDescriptor(
        id="adadecode",
        name="AdaDecode",
        source_url="https://github.com/weizhepei/AdaDecode",
        kind=OptimizationKind.DECODE,
        maturity=OptimizationMaturity.BLOCKED,
        integration_mode=IntegrationMode.RESEARCH_ONLY,
        license="No repository license",
        summary="Adaptive layer-parallel decoding with trained intermediate prediction heads.",
        supported_engines=("transformers",),
        supported_compute=("cuda",),
        supported_os=("linux",),
        limitations=(
            "No source-code license is present, so code cannot be incorporated.",
            "Requires task/model-specific trained prediction heads and execution-graph changes.",
        ),
        composition_domains=("speculative_decode",),
    ),
    OptimizationDescriptor(
        id="resonance_yarn",
        name="Resonance YaRN",
        source_url="https://github.com/sheryc/resonance_rope",
        kind=OptimizationKind.POSITION_ENCODING,
        maturity=OptimizationMaturity.RESEARCH,
        integration_mode=IntegrationMode.NATIVE_BACKEND_REQUIRED,
        license="Apache-2.0",
        summary="Resonance wavelength rounding applied to YaRN positional embeddings.",
        supported_engines=("transformers",),
        supported_compute=("cuda",),
        supported_os=("linux",),
        limitations=(
            "The provided llama_finetuning code is a Hugging Face training fork, not a llama.cpp plugin.",
            "llama.cpp or Godzilla requires a native RoPE implementation and model-level validation.",
        ),
        composition_domains=("position_encoding",),
    ),
    OptimizationDescriptor(
        id="jetspec",
        name="JetSpec",
        source_url="https://github.com/hao-ai-lab/JetSpec",
        kind=OptimizationKind.DECODE,
        maturity=OptimizationMaturity.EXPERIMENTAL,
        integration_mode=IntegrationMode.OPTIONAL_PYTHON,
        license="MIT",
        summary="Causal-parallel tree speculative decoding with trained draft heads.",
        supported_engines=("jetspec",),
        supported_compute=("cuda",),
        supported_os=("linux",),
        supported_kv_formats=("fp16", "bf16"),
        required_modules=("jetspec",),
        composition_domains=("runtime_engine", "speculative_decode"),
        required_artifacts=("A JetSpec draft head matching the exact target model",),
        validation_gates=(
            "Greedy output parity against the same unmodified target model",
            "Acceptance length, tokens/second, and VRAM on the target GPU",
        ),
        quality_risk=QualityRisk.EXACT,
        reviewed_source_commit="2c7b3fae75690dfe9a188a37d7fdfd43ee0e032f",
        limitations=(
            "The optimized engine and vLLM integration are separate runtimes, not Godzilla plugins.",
            "Published headline performance uses NVIDIA B200 GPUs and model-specific draft heads.",
        ),
    ),
    OptimizationDescriptor(
        id="lucebox",
        name="Lucebox",
        source_url="https://github.com/Luce-Org/lucebox",
        kind=OptimizationKind.DECODE,
        maturity=OptimizationMaturity.EXPERIMENTAL,
        integration_mode=IntegrationMode.EXTERNAL_SERVICE,
        license="Apache-2.0",
        summary="Separate native GGUF inference server with DFlash, PFlash, KVFlash, and hardware-specific kernels.",
        supported_engines=("lucebox",),
        supported_compute=("cuda", "rocm"),
        supported_os=("linux",),
        composition_domains=("runtime_engine",),
        required_artifacts=("A supported target GGUF and any model-specific drafter or scorer GGUF",),
        validation_gates=(
            "Binary capability scan before command generation",
            "Direct-path output baseline before enabling lossy prompt compression",
        ),
        quality_risk=QualityRisk.CONDITIONAL,
        reviewed_source_commit="ac22a3ed2b555e7211d730e7372807ae07e6df3b",
        limitations=(
            "Lucebox is a complete runtime and must not be installed into another llama.cpp fork.",
            "Each optimization is model- and hardware-specific; unsupported combinations remain disabled.",
        ),
    ),
    OptimizationDescriptor(
        id="proxima",
        name="Proxima / STAR-KV",
        source_url="https://github.com/Tenosra/Proxima",
        kind=OptimizationKind.CACHE_REPRESENTATION,
        maturity=OptimizationMaturity.EXPERIMENTAL,
        integration_mode=IntegrationMode.OPTIONAL_PYTHON,
        license="Apache-2.0",
        summary="Source-only vLLM plugin for calibrated low-rank KV-cache compression.",
        supported_engines=("vllm",),
        supported_compute=("cuda",),
        supported_os=("linux",),
        required_modules=("proxima_vllm",),
        composition_domains=("kv_representation", "attention_kernel"),
        required_artifacts=("A STAR-KV checkpoint calibrated from the exact base model",),
        validation_gates=(
            "vLLM 0.10.1.1 import and plugin registration",
            "Perplexity and long-context task quality against uncompressed vLLM",
        ),
        quality_risk=QualityRisk.LOSSY,
        reviewed_source_commit="a9ffc476e520958cb3defa8289620647c60a9a8b",
        limitations=(
            "Not published on PyPI and intentionally pinned to vLLM 0.10.1.1.",
            "The reference calibrated checkpoint is private and multi-model hardware support is unverified.",
        ),
    ),
    OptimizationDescriptor(
        id="jetlong",
        name="Jet-Long",
        source_url="https://github.com/jet-ai-projects/jet-long",
        kind=OptimizationKind.POSITION_ENCODING,
        maturity=OptimizationMaturity.EXPERIMENTAL,
        integration_mode=IntegrationMode.OPTIONAL_PYTHON,
        license="Apache-2.0",
        summary="Training-free Qwen3 context extension with YaRN, DCA, JetLong, and JetLongFreq variants.",
        supported_engines=("transformers",),
        supported_compute=("cuda",),
        supported_os=("linux",),
        required_modules=("jetlm",),
        composition_domains=("position_encoding",),
        allows_composition_with=("resonance_jetlong",),
        required_artifacts=("An exact supported Qwen3 base checkpoint and generated method configuration",),
        validation_gates=(
            "Base-window regression and PG-19 perplexity",
            "RULER, HELMET, and long-context retrieval at every claimed length",
        ),
        quality_risk=QualityRisk.CONDITIONAL,
        reviewed_source_commit="e5d4dce8fc9b9ffd31d975940f26fb9dd92528b6",
        limitations=(
            "The reviewed implementation targets Qwen3 base models and exact dependency versions.",
            "The fused profile requires SM90/H100 and CUDA 13 and is not enabled by the default profile.",
        ),
    ),
    OptimizationDescriptor(
        id="chunkllama",
        name="ChunkLlama / Dual Chunk Attention",
        source_url="https://github.com/HKUNLP/ChunkLlama",
        kind=OptimizationKind.POSITION_ENCODING,
        maturity=OptimizationMaturity.RESEARCH,
        integration_mode=IntegrationMode.RESEARCH_ONLY,
        license="Apache-2.0 code; CC-BY-NC-4.0 data and weights",
        summary="Reference DCA implementation for Llama/Qwen long-context research.",
        supported_engines=("transformers", "vllm"),
        supported_compute=("cuda",),
        supported_os=("linux",),
        composition_domains=("position_encoding", "attention_topology"),
        quality_risk=QualityRisk.RESEARCH,
        reviewed_source_commit="2add4d7c99d24dcc1ab03414cc602abb2e28cf2c",
        limitations=(
            "Jet-Long already contains a newer DCA implementation for its supported Qwen3 path.",
            "The upstream vLLM/Transformers stack is old and data or weights may be non-commercial.",
        ),
    ),
    OptimizationDescriptor(
        id="rabitqcache",
        name="RaBitQCache",
        source_url="https://github.com/Sakuraaa0/RaBitQCache",
        kind=OptimizationKind.TOKEN_POLICY,
        maturity=OptimizationMaturity.BLOCKED,
        integration_mode=IntegrationMode.RESEARCH_ONLY,
        license="No repository software license",
        summary="Adaptive sparse KV retrieval using rotated binary quantization.",
        supported_engines=("transformers", "vllm"),
        supported_compute=("cuda",),
        supported_os=("linux",),
        composition_domains=("kv_selection", "attention_kernel"),
        quality_risk=QualityRisk.RESEARCH,
        reviewed_source_commit="9eddbbdb5979fd518ef651041a1f9ca5546d46b1",
        limitations=(
            "No software license currently permits incorporation or redistribution.",
            "The serving path is a large CUDA 12.8+ vLLM fork rather than a maintained plugin.",
        ),
    ),
    OptimizationDescriptor(
        id="scope_pe",
        name="ScoPE",
        source_url="https://github.com/oncemoe/ScoPE",
        kind=OptimizationKind.POSITION_ENCODING,
        maturity=OptimizationMaturity.RESEARCH,
        integration_mode=IntegrationMode.RESEARCH_ONLY,
        license="BSD-3-Clause",
        summary="TorchTitan training framework for scoped positional encoding and per-head attention masks.",
        supported_engines=("torchtitan",),
        supported_compute=("cuda",),
        supported_os=("linux",),
        composition_domains=("position_encoding", "attention_topology"),
        required_artifacts=("A model trained with ScoPE-compatible architecture and masks",),
        quality_risk=QualityRisk.RESEARCH,
        reviewed_source_commit="5e9c3cd47e0415544178389c9552912d569cacb6",
        limitations=(
            "ScoPE is primarily a pretraining system, not a retrofit for arbitrary checkpoints.",
            "Its package identifies as TorchTitan and requires recent FlexAttention support.",
        ),
    ),
    OptimizationDescriptor(
        id="duoattention",
        name="DuoAttention",
        source_url="https://github.com/mit-han-lab/duo-attention",
        kind=OptimizationKind.TOKEN_POLICY,
        maturity=OptimizationMaturity.RESEARCH,
        integration_mode=IntegrationMode.RESEARCH_ONLY,
        license="MIT",
        summary="Per-head retrieval/streaming KV policy for selected long-context models.",
        supported_engines=("transformers",),
        supported_compute=("cuda",),
        supported_os=("linux",),
        composition_domains=("kv_selection", "attention_topology"),
        required_artifacts=("Retrieval-head patterns calibrated for the exact model",),
        validation_gates=(
            "Needle-in-a-haystack and long-context accuracy against full attention",
            "Native Block-Sparse-Attention and FlashInfer kernel checks",
        ),
        quality_risk=QualityRisk.LOSSY,
        reviewed_source_commit="fe93c314ae87306ef6629dc16713250b4718ffe7",
        limitations=(
            "Pretrained head patterns cover only a small reviewed model set.",
            "The documented environment builds several version-sensitive CUDA extensions.",
        ),
    ),
    OptimizationDescriptor(
        id="icecache",
        name="IceCache",
        source_url="https://github.com/yuzhenmao/IceCache",
        kind=OptimizationKind.CACHE_STORAGE,
        maturity=OptimizationMaturity.RESEARCH,
        integration_mode=IntegrationMode.RESEARCH_ONLY,
        license="MIT",
        summary="CPU-offloaded KV pages with approximate M-DCI retrieval.",
        supported_engines=("transformers",),
        supported_compute=("cuda",),
        supported_os=("linux",),
        required_capabilities=("openblas", "high_cpu_parallelism"),
        composition_domains=("cache_storage", "kv_selection"),
        required_artifacts=("Matching IceCache and M-DCI source checkouts",),
        validation_gates=(
            "IceCache CUDA extension and M-DCI native import checks",
            "TTFT, retrieval quality, and CPU saturation at the selected page budget",
        ),
        quality_risk=QualityRisk.LOSSY,
        reviewed_source_commit="6a7ecfd9c710c1b3170b2f5931d048fad0f04b22",
        limitations=(
            "Requires two native source builds plus GCC, CMake, OpenBLAS, and OpenMP.",
            "Upstream recommends at least 64 CPU threads for useful TTFT.",
        ),
    ),
    OptimizationDescriptor(
        id="pflash_llamacpp",
        name="llama.cpp PFlash/KVFlash fork",
        source_url="https://github.com/HawgAuto/llama.cpp-dflash-pflash-kvflash",
        kind=OptimizationKind.PREFILL,
        maturity=OptimizationMaturity.RESEARCH,
        integration_mode=IntegrationMode.EXTERNAL_SERVICE,
        license="MIT",
        summary="Separate llama.cpp server fork with experimental PFlash, KVFlash, DFlash, and routing controls.",
        supported_engines=("pflash_llamacpp",),
        supported_compute=("cuda",),
        supported_os=("linux",),
        composition_domains=("runtime_engine",),
        required_artifacts=("Target, drafter, and scorer GGUFs matching the selected runtime path",),
        validation_gates=(
            "Binary help/capability scan and direct-server baseline",
            "Exact-task bypass and direct verification for lossy PFlash routes",
        ),
        quality_risk=QualityRisk.LOSSY,
        reviewed_source_commit="b68585def475187e7d22b10b9e40cb1835de79b1",
        limitations=(
            "This is a separate experimental fork, not a patch for arbitrary Godzilla trees.",
            "PFlash can omit prompt facts and must remain disabled for exact extraction and code tasks.",
        ),
    ),
    OptimizationDescriptor(
        id="godzilla_composition",
        name="Pinned Godzilla PFlash/KVFlash composition",
        source_url="https://github.com/aivrar/multi-turboquant",
        kind=OptimizationKind.PREFILL,
        maturity=OptimizationMaturity.EXPERIMENTAL,
        integration_mode=IntegrationMode.NATIVE_BACKEND_REQUIRED,
        license="MIT",
        summary=(
            "Exact-commit Godzilla overlay with request-gated PFlash and bounded "
            "whole-idle-slot KVFlash residency."
        ),
        supported_engines=("godzilla",),
        supported_compute=("cpu", "cuda"),
        supported_os=("windows", "linux"),
        supported_architectures=("x86_64", "amd64"),
        composition_domains=("prefill_policy", "server_kv_residency"),
        required_executables=("git", "cmake"),
        required_artifacts=(
            "A new source tree prepared from Godzilla commit 09214b160b402011359f0ef9d5fa8f8be1112e85",
            "A workload-specific quality corpus before enabling PFlash",
        ),
        validation_gates=(
            "Hash-bounded source inspection and exact-commit llama-server build",
            "PFlash off/on quality, exact-task bypass, TTFT, and prompt-cache regression",
            "KVFlash resident-budget, LRU eviction, concurrency, and long-context soak tests",
        ),
        quality_risk=QualityRisk.LOSSY,
        reviewed_source_commit="09214b160b402011359f0ef9d5fa8f8be1112e85",
        limitations=(
            "PFlash is off by default, must be enabled at startup and per request, and skips chat, multimodal, embedding, rerank, and parallel-parent tasks.",
            "KVFlash manages complete idle slots only; arbitrary KV-page restore, disk restore, and prefill skipping are not implemented or claimed.",
            "TriAttention and KVarN remain mutually exclusive in the pinned upstream revision.",
            "SpecLA is not included because it is a specialized linear-attention runtime rather than a stackable Godzilla add-on.",
        ),
    ),
    OptimizationDescriptor(
        id="resonance_jetlong",
        name="Resonance JetLongFreq research profile",
        source_url="https://github.com/sheryc/resonance_rope",
        kind=OptimizationKind.POSITION_ENCODING,
        maturity=OptimizationMaturity.RESEARCH,
        integration_mode=IntegrationMode.NATIVE_BACKEND_REQUIRED,
        license="Apache-2.0",
        summary="Experimental Resonance wavelength rounding applied to Jet-Long's YaRN-based frequency variant.",
        supported_engines=("transformers",),
        supported_compute=("cuda",),
        supported_os=("linux",),
        requires=("jetlong",),
        composition_domains=("position_encoding",),
        allows_composition_with=("jetlong",),
        required_artifacts=("A separate generated JetLongFreq-Resonance model configuration",),
        validation_gates=(
            "Base-window logits and perplexity regression",
            "PG-19, RULER, HELMET, passkey, and needle retrieval across claimed lengths",
        ),
        quality_risk=QualityRisk.RESEARCH,
        limitations=(
            "Upstream Resonance LLM experiments covered Llama-2 fine-tuning, not Qwen3 Jet-Long.",
            "Plain JetLong uses grouped positions rather than YaRN; only the YaRN/JetLongFreq path is composable.",
        ),
    ),
)


def create_builtin_registry() -> OptimizationRegistry:
    registry = OptimizationRegistry()
    for descriptor in BUILTIN_DESCRIPTORS:
        registry.register(ManifestPlugin(descriptor))
    return registry
